version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - docker-selenium

  chrome:
    image: selenium/node-chrome:3.141.59-bismuth
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - docker-selenium

  firefox:
    image: selenium/node-firefox:3.141.59-bismuth
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - docker-selenium
  testng:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    depends_on:
      - selenium-huub
      - chrome
      - firefox
    networks:
      - docker-selenium
    volumes:
      $PWD:/usr/app




